// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type FooterDocumentDataSlicesSlice = FooterSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;

type HeaderDocumentDataSlicesSlice = HeaderSlice;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Slice Zone field in *Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HeaderDocumentData>, "header", Lang>;

type RecensioneDocumentDataSlicesSlice =
  | PreFooterSlice
  | TestoRecensioneSlice
  | HeroRecensioneSlice;

/**
 * Content for Recensione documents
 */
interface RecensioneDocumentData {
  /**
   * Numero field in *Recensione*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: recensione.numero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  numero: prismic.NumberField;

  /**
   * Slice Zone field in *Recensione*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: recensione.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<RecensioneDocumentDataSlicesSlice> /**
   * Meta Title field in *Recensione*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: recensione.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Recensione*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: recensione.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Recensione*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: recensione.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Recensione document from Prismic
 *
 * - **API ID**: `recensione`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RecensioneDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<RecensioneDocumentData>,
    "recensione",
    Lang
  >;

type SaraDocumentDataSlicesSlice = BioSlice | HeroSlice;

/**
 * Content for Sara Bianchi | Sceneggiatrice - Story editor - Regista documents
 */
interface SaraDocumentData {
  /**
   * Slice Zone field in *Sara Bianchi | Sceneggiatrice - Story editor - Regista*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sara.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SaraDocumentDataSlicesSlice> /**
   * Meta Title field in *Sara Bianchi | Sceneggiatrice - Story editor - Regista*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: sara.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Sara Bianchi | Sceneggiatrice - Story editor - Regista*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: sara.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Sara Bianchi | Sceneggiatrice - Story editor - Regista*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sara.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Sara Bianchi | Sceneggiatrice - Story editor - Regista document from Prismic
 *
 * - **API ID**: `sara`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SaraDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SaraDocumentData>, "sara", Lang>;

type ScriptDocumentDataSlicesSlice = ScriptSlice | HeroScriptSlice;

/**
 * Content for Script documents
 */
interface ScriptDocumentData {
  /**
   * Numero field in *Script*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: script.numero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  numero: prismic.NumberField;

  /**
   * Slice Zone field in *Script*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: script.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ScriptDocumentDataSlicesSlice> /**
   * Meta Title field in *Script*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: script.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Script*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: script.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Script*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: script.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Script document from Prismic
 *
 * - **API ID**: `script`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ScriptDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ScriptDocumentData>, "script", Lang>;

type SettingsDocumentDataSlicesSlice = ColorsSlice;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type VideoDocumentDataSlicesSlice =
  | VideoVimeoSlice
  | SelezioneSlice
  | SinossiSlice
  | SpecsSlice
  | VideoEmbedSlice
  | HeroVideoSlice;

/**
 * Content for Video documents
 */
interface VideoDocumentData {
  /**
   * Numero field in *Video*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: video.numero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  numero: prismic.NumberField;

  /**
   * Slice Zone field in *Video*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: video.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<VideoDocumentDataSlicesSlice> /**
   * Meta Title field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: video.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: video.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Video*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Video document from Prismic
 *
 * - **API ID**: `video`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VideoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<VideoDocumentData>, "video", Lang>;

export type AllDocumentTypes =
  | FooterDocument
  | HeaderDocument
  | RecensioneDocument
  | SaraDocument
  | ScriptDocument
  | SettingsDocument
  | VideoDocument;

/**
 * Primary content in *Bio → Default → Primary*
 */
export interface BioSliceDefaultPrimary {
  /**
   * Titolo field in *Bio → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Testo bio field in *Bio → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio.default.primary.testo_bio
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testo_bio: prismic.RichTextField;

  /**
   * Immagine bio field in *Bio → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bio.default.primary.immagine_bio
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_bio: prismic.ImageField<never>;
}

/**
 * Default variation for Bio Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BioSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BioSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Bio*
 */
type BioSliceVariation = BioSliceDefault;

/**
 * Bio Shared Slice
 *
 * - **API ID**: `bio`
 * - **Description**: Bio
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BioSlice = prismic.SharedSlice<"bio", BioSliceVariation>;

/**
 * Primary content in *Colors → Default → Primary*
 */
export interface ColorsSliceDefaultPrimary {
  /**
   * Primary field in *Colors → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: colors.default.primary.primary
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary: prismic.KeyTextField;

  /**
   * Secondary field in *Colors → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: colors.default.primary.secondary
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary: prismic.KeyTextField;

  /**
   * Tertiary field in *Colors → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: colors.default.primary.tertiary
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tertiary: prismic.KeyTextField;
}

/**
 * Default variation for Colors Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ColorsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ColorsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Colors*
 */
type ColorsSliceVariation = ColorsSliceDefault;

/**
 * Colors Shared Slice
 *
 * - **API ID**: `colors`
 * - **Description**: Colors
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ColorsSlice = prismic.SharedSlice<"colors", ColorsSliceVariation>;

/**
 * Item in *Footer → Default → Primary → Social*
 */
export interface FooterSliceDefaultPrimarySocialItem {
  /**
   * Logo social field in *Footer → Default → Primary → Social*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.social[].logo_social
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_social: prismic.ImageField<never>;

  /**
   * Link Social field in *Footer → Default → Primary → Social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.social[].link_social
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_social: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Testo primario field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.testo_primario
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_primario: prismic.KeyTextField;

  /**
   * Testo secondario field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.testo_secondario
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_secondario: prismic.KeyTextField;

  /**
   * Mail field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.mail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mail: prismic.KeyTextField;

  /**
   * Social field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.social[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social: prismic.GroupField<Simplify<FooterSliceDefaultPrimarySocialItem>>;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Item in *Header → Default → Primary → Menu*
 */
export interface HeaderSliceDefaultPrimaryMenuItem {
  /**
   * Menu label field in *Header → Default → Primary → Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.menu[].menu_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_label: prismic.KeyTextField;

  /**
   * Slug field in *Header → Default → Primary → Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.menu[].slug
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  slug: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * Nome sito field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.nome_sito
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_sito: prismic.KeyTextField;

  /**
   * Payoff field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.payoff
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  payoff: prismic.KeyTextField;

  /**
   * Menu field in *Header → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.menu[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu: prismic.GroupField<Simplify<HeaderSliceDefaultPrimaryMenuItem>>;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Hero backgorund field in *Hero → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_backgorund
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  hero_backgorund: prismic.EmbedField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *HeroRecensione → Default → Primary*
 */
export interface HeroRecensioneSliceDefaultPrimary {
  /**
   * Background field in *HeroRecensione → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_recensione.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;

  /**
   * Titolo field in *HeroRecensione → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_recensione.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Specs field in *HeroRecensione → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_recensione.default.primary.specs
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  specs: prismic.KeyTextField;

  /**
   * Pubblicazione field in *HeroRecensione → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_recensione.default.primary.pubblicazione
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pubblicazione: prismic.KeyTextField;

  /**
   * Titolo articolo field in *HeroRecensione → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_recensione.default.primary.titolo_articolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo_articolo: prismic.KeyTextField;
}

/**
 * Default variation for HeroRecensione Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroRecensioneSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroRecensioneSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroRecensione*
 */
type HeroRecensioneSliceVariation = HeroRecensioneSliceDefault;

/**
 * HeroRecensione Shared Slice
 *
 * - **API ID**: `hero_recensione`
 * - **Description**: HeroRecensione
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroRecensioneSlice = prismic.SharedSlice<
  "hero_recensione",
  HeroRecensioneSliceVariation
>;

/**
 * Primary content in *HeroScript → Default → Primary*
 */
export interface HeroScriptSliceDefaultPrimary {
  /**
   * Titolo field in *HeroScript → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_script.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Tipo Script field in *HeroScript → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_script.default.primary.tipo_script
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tipo_script: prismic.KeyTextField;

  /**
   * Colore homepage field in *HeroScript → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_script.default.primary.colore
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  colore: prismic.KeyTextField;
}

/**
 * Default variation for HeroScript Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroScriptSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroScriptSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroScript*
 */
type HeroScriptSliceVariation = HeroScriptSliceDefault;

/**
 * HeroScript Shared Slice
 *
 * - **API ID**: `hero_script`
 * - **Description**: HeroScript
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroScriptSlice = prismic.SharedSlice<
  "hero_script",
  HeroScriptSliceVariation
>;

/**
 * Primary content in *HeroVideo → Default → Primary*
 */
export interface HeroVideoSliceDefaultPrimary {
  /**
   * Background image field in *HeroVideo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_video.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Titolo field in *HeroVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_video.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Genere field in *HeroVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_video.default.primary.genere
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  genere: prismic.KeyTextField;

  /**
   * Info extra field in *HeroVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_video.default.primary.info_extra
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info_extra: prismic.KeyTextField;

  /**
   * Tipo Video field in *HeroVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_video.default.primary.tipovideo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tipovideo: prismic.KeyTextField;
}

/**
 * Default variation for HeroVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroVideo*
 */
type HeroVideoSliceVariation = HeroVideoSliceDefault;

/**
 * HeroVideo Shared Slice
 *
 * - **API ID**: `hero_video`
 * - **Description**: HeroVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroVideoSlice = prismic.SharedSlice<
  "hero_video",
  HeroVideoSliceVariation
>;

/**
 * Primary content in *PreFooter → Default → Primary*
 */
export interface PreFooterSliceDefaultPrimary {
  /**
   * Originale field in *PreFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_footer.default.primary.originale
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  originale: prismic.KeyTextField;

  /**
   * Link field in *PreFooter → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_footer.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for PreFooter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PreFooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PreFooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PreFooter*
 */
type PreFooterSliceVariation = PreFooterSliceDefault;

/**
 * PreFooter Shared Slice
 *
 * - **API ID**: `pre_footer`
 * - **Description**: PreFooter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PreFooterSlice = prismic.SharedSlice<
  "pre_footer",
  PreFooterSliceVariation
>;

/**
 * Primary content in *Script → Default → Primary*
 */
export interface ScriptSliceDefaultPrimary {
  /**
   * Script pdf field in *Script → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: script.default.primary.script_pdf
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  script_pdf: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for Script Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScriptSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScriptSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Script*
 */
type ScriptSliceVariation = ScriptSliceDefault;

/**
 * Script Shared Slice
 *
 * - **API ID**: `script`
 * - **Description**: Script
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScriptSlice = prismic.SharedSlice<"script", ScriptSliceVariation>;

/**
 * Item in *Selezione → Default → Primary → Selezione*
 */
export interface SelezioneSliceDefaultPrimarySelezioneItem {
  /**
   * NomeSelezione field in *Selezione → Default → Primary → Selezione*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: selezione.default.primary.selezione[].nomeselezione
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nomeselezione: prismic.KeyTextField;
}

/**
 * Primary content in *Selezione → Default → Primary*
 */
export interface SelezioneSliceDefaultPrimary {
  /**
   * Titolo field in *Selezione → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: selezione.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Selezione field in *Selezione → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: selezione.default.primary.selezione[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  selezione: prismic.GroupField<
    Simplify<SelezioneSliceDefaultPrimarySelezioneItem>
  >;
}

/**
 * Default variation for Selezione Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SelezioneSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SelezioneSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Selezione*
 */
type SelezioneSliceVariation = SelezioneSliceDefault;

/**
 * Selezione Shared Slice
 *
 * - **API ID**: `selezione`
 * - **Description**: Selezione
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SelezioneSlice = prismic.SharedSlice<
  "selezione",
  SelezioneSliceVariation
>;

/**
 * Primary content in *Sinossi → Default → Primary*
 */
export interface SinossiSliceDefaultPrimary {
  /**
   * Titolo field in *Sinossi → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sinossi.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Sinossi field in *Sinossi → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sinossi.default.primary.sinossi
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sinossi: prismic.RichTextField;
}

/**
 * Default variation for Sinossi Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SinossiSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SinossiSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Sinossi*
 */
type SinossiSliceVariation = SinossiSliceDefault;

/**
 * Sinossi Shared Slice
 *
 * - **API ID**: `sinossi`
 * - **Description**: Sinossi
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SinossiSlice = prismic.SharedSlice<
  "sinossi",
  SinossiSliceVariation
>;

/**
 * Item in *Specs → Default → Primary → Specs*
 */
export interface SpecsSliceDefaultPrimarySpecsItem {
  /**
   * Chiave field in *Specs → Default → Primary → Specs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: specs.default.primary.specs[].chiave
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  chiave: prismic.KeyTextField;

  /**
   * Valore field in *Specs → Default → Primary → Specs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: specs.default.primary.specs[].valore
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  valore: prismic.KeyTextField;
}

/**
 * Primary content in *Specs → Default → Primary*
 */
export interface SpecsSliceDefaultPrimary {
  /**
   * Titolo field in *Specs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: specs.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Specs field in *Specs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: specs.default.primary.specs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  specs: prismic.GroupField<Simplify<SpecsSliceDefaultPrimarySpecsItem>>;
}

/**
 * Default variation for Specs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpecsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpecsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Specs*
 */
type SpecsSliceVariation = SpecsSliceDefault;

/**
 * Specs Shared Slice
 *
 * - **API ID**: `specs`
 * - **Description**: Specs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpecsSlice = prismic.SharedSlice<"specs", SpecsSliceVariation>;

/**
 * Primary content in *TestoRecensione → Default → Primary*
 */
export interface TestoRecensioneSliceDefaultPrimary {
  /**
   * Testo Recensione field in *TestoRecensione → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testo_recensione.default.primary.testorecensione
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testorecensione: prismic.RichTextField;
}

/**
 * Default variation for TestoRecensione Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestoRecensioneSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestoRecensioneSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TestoRecensione*
 */
type TestoRecensioneSliceVariation = TestoRecensioneSliceDefault;

/**
 * TestoRecensione Shared Slice
 *
 * - **API ID**: `testo_recensione`
 * - **Description**: TestoRecensione
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestoRecensioneSlice = prismic.SharedSlice<
  "testo_recensione",
  TestoRecensioneSliceVariation
>;

/**
 * Primary content in *VideoEmbed → Default → Primary*
 */
export interface VideoEmbedSliceDefaultPrimary {
  /**
   * VideoEmbed field in *VideoEmbed → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: video_embed.default.primary.videoembed
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  videoembed: prismic.EmbedField;
}

/**
 * Default variation for VideoEmbed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoEmbedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoEmbedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoEmbed*
 */
type VideoEmbedSliceVariation = VideoEmbedSliceDefault;

/**
 * VideoEmbed Shared Slice
 *
 * - **API ID**: `video_embed`
 * - **Description**: VideoEmbed
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoEmbedSlice = prismic.SharedSlice<
  "video_embed",
  VideoEmbedSliceVariation
>;

/**
 * Primary content in *VideoVimeo → Default → Primary*
 */
export interface VideoVimeoSliceDefaultPrimary {
  /**
   * linkVimeo field in *VideoVimeo → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: video_vimeo.default.primary.linkvimeo
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkvimeo: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for VideoVimeo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoVimeoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoVimeoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoVimeo*
 */
type VideoVimeoSliceVariation = VideoVimeoSliceDefault;

/**
 * VideoVimeo Shared Slice
 *
 * - **API ID**: `video_vimeo`
 * - **Description**: VideoVimeo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoVimeoSlice = prismic.SharedSlice<
  "video_vimeo",
  VideoVimeoSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      RecensioneDocument,
      RecensioneDocumentData,
      RecensioneDocumentDataSlicesSlice,
      SaraDocument,
      SaraDocumentData,
      SaraDocumentDataSlicesSlice,
      ScriptDocument,
      ScriptDocumentData,
      ScriptDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSlicesSlice,
      VideoDocument,
      VideoDocumentData,
      VideoDocumentDataSlicesSlice,
      AllDocumentTypes,
      BioSlice,
      BioSliceDefaultPrimary,
      BioSliceVariation,
      BioSliceDefault,
      ColorsSlice,
      ColorsSliceDefaultPrimary,
      ColorsSliceVariation,
      ColorsSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimarySocialItem,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeaderSlice,
      HeaderSliceDefaultPrimaryMenuItem,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroRecensioneSlice,
      HeroRecensioneSliceDefaultPrimary,
      HeroRecensioneSliceVariation,
      HeroRecensioneSliceDefault,
      HeroScriptSlice,
      HeroScriptSliceDefaultPrimary,
      HeroScriptSliceVariation,
      HeroScriptSliceDefault,
      HeroVideoSlice,
      HeroVideoSliceDefaultPrimary,
      HeroVideoSliceVariation,
      HeroVideoSliceDefault,
      PreFooterSlice,
      PreFooterSliceDefaultPrimary,
      PreFooterSliceVariation,
      PreFooterSliceDefault,
      ScriptSlice,
      ScriptSliceDefaultPrimary,
      ScriptSliceVariation,
      ScriptSliceDefault,
      SelezioneSlice,
      SelezioneSliceDefaultPrimarySelezioneItem,
      SelezioneSliceDefaultPrimary,
      SelezioneSliceVariation,
      SelezioneSliceDefault,
      SinossiSlice,
      SinossiSliceDefaultPrimary,
      SinossiSliceVariation,
      SinossiSliceDefault,
      SpecsSlice,
      SpecsSliceDefaultPrimarySpecsItem,
      SpecsSliceDefaultPrimary,
      SpecsSliceVariation,
      SpecsSliceDefault,
      TestoRecensioneSlice,
      TestoRecensioneSliceDefaultPrimary,
      TestoRecensioneSliceVariation,
      TestoRecensioneSliceDefault,
      VideoEmbedSlice,
      VideoEmbedSliceDefaultPrimary,
      VideoEmbedSliceVariation,
      VideoEmbedSliceDefault,
      VideoVimeoSlice,
      VideoVimeoSliceDefaultPrimary,
      VideoVimeoSliceVariation,
      VideoVimeoSliceDefault,
    };
  }
}
