// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bio: dynamic(() => import("./Bio")),
  colors: dynamic(() => import("./Colors")),
  header: dynamic(() => import("./Header")),
  hero: dynamic(() => import("./Hero")),
  hero_video: dynamic(() => import("./HeroVideo")),
  video_embed: dynamic(() => import("./VideoEmbed")),
};
