// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bio: dynamic(() => import("./Bio")),
  colors: dynamic(() => import("./Colors")),
  footer: dynamic(() => import("./Footer")),
  header: dynamic(() => import("./Header")),
  hero: dynamic(() => import("./Hero")),
  hero_script: dynamic(() => import("./HeroScript")),
  hero_video: dynamic(() => import("./HeroVideo")),
  script: dynamic(() => import("./Script")),
  selezione: dynamic(() => import("./Selezione")),
  sinossi: dynamic(() => import("./Sinossi")),
  specs: dynamic(() => import("./Specs")),
  video_embed: dynamic(() => import("./VideoEmbed")),
  video_vimeo: dynamic(() => import("./VideoVimeo")),
};
